version: "2"
services:
  postgres:
    image: postgres:9.6
    ports:
      - "2224:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wdm
  server:
    build:
      context: .
    command: "npm run dev"
    ports:
      - "2222:3000"
    volumes:
      - .:/var/www
    links:
      - postgres:postgres
      - mongo:mongo
  mongo:
    image: mongo:3.0
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "2223:27017"
  neo4j:
    image: neo4j:3.2
    volumes:
      - ./data/neo4j:/data
    ports:
      - "2225:7687"
      - "2226:7474"
    environment:
      NEO4J_AUTH: none
