version: "2"
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wdm
  server:
    build:
      context: ./src
    command: "npm run dev"
    ports:
      - "2222:80"
    volumes:
      - ./src:/var/www
    links:
      - postgres:postgres

