version: "2"
services:
  postgres:
    image: postgres:9.6
    ports:
      - "2224:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wdm
  server:
    build:
      context: .
    command: "npm run dev"
    ports:
      - "2222:3000"
    volumes:
      - .:/var/www
    links:
      - postgres:postgres
      - mongo1:mongo
  mongo1:
    image: mongo:3
    volumes:
      - ./data/mongo1:/data/db
    ports:
      - "22231:27017"
    networks:
      - "mongo"
    command: "mongod --replSet mongo-replication --smallfiles"
  mongo2:
    image: mongo:3
    volumes:
      - ./data/mongo2:/data/db
    ports:
      - "22232:27017"
    networks:
      - "mongo"
    command: "mongod --replSet mongo-replication --smallfiles"
  mongo3:
    image: mongo:3
    volumes:
      - ./data/mongo3:/data/db
    ports:
      - "22233:27017"
    networks:
      - "mongo"
    command: "mongod --replSet mongo-replication --smallfiles"
  neo4j:
    image: neo4j:3.2
    volumes:
      - ./data/neo4j:/data
    ports:
      - "2225:7687"
      - "2226:7474"
    environment:
      NEO4J_AUTH: none
networks:
  mongo:
    driver: bridge
